-- MySQL Script generated by MySQL Workbench
-- Sun Mar  3 16:19:59 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema WMkTranslation
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema WMkTranslation
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `WMkTranslation` DEFAULT CHARACTER SET utf8 ;
USE `WMkTranslation` ;

-- -----------------------------------------------------
-- Table `WMkTranslation`.`Language`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WMkTranslation`.`Language` ;

CREATE TABLE IF NOT EXISTS `WMkTranslation`.`Language` (
  `LanguageId` CHAR(36) NOT NULL,
  `Name` NVARCHAR(46) NOT NULL,
  `Description` NVARCHAR(60) NOT NULL,
  PRIMARY KEY (`LanguageId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WMkTranslation`.`Customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WMkTranslation`.`Customer` ;

CREATE TABLE IF NOT EXISTS `WMkTranslation`.`Customer` (
  `CustomerId` CHAR(36) NOT NULL,
  `Name` NVARCHAR(45) NOT NULL,
  `Email` NVARCHAR(45) NOT NULL,
  `TelephoneNo` NVARCHAR(45) NOT NULL,
  `Address` NVARCHAR(100) NOT NULL,
  PRIMARY KEY (`CustomerId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WMkTranslation`.`Translator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WMkTranslation`.`Translator` ;

CREATE TABLE IF NOT EXISTS `WMkTranslation`.`Translator` (
  `TranslatorId` CHAR(36) NOT NULL,
  `Name` VARCHAR(45) NULL,
  `DateofStart` DATE NULL,
  `Address` NVARCHAR(100) NULL,
  PRIMARY KEY (`TranslatorId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `WMkTranslation`.`TranslationOrder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WMkTranslation`.`TranslationOrder` ;

CREATE TABLE IF NOT EXISTS `WMkTranslation`.`TranslationOrder` (
  `TranslationOrderId` CHAR(36) NOT NULL,
  `OrderDate` DATE NOT NULL,
  `TranslationType` VARCHAR(45) NOT NULL,
  `Price` DECIMAL NOT NULL,
  `LanguageId` CHAR(36) NOT NULL,
  `CustomerId` CHAR(36) NOT NULL,
  `TranslatorId` CHAR(36) NOT NULL,
  PRIMARY KEY (`TranslationOrderId`),
  INDEX `fk_TranslationOrder_Language_idx` (`LanguageId` ASC) VISIBLE,
  INDEX `fk_TranslationOrder_Customer1_idx` (`CustomerId` ASC) VISIBLE,
  INDEX `fk_TranslationOrder_Translator1_idx` (`TranslatorId` ASC) VISIBLE,
  CONSTRAINT `fk_TranslationOrder_Language`
    FOREIGN KEY (`LanguageId`)
    REFERENCES `WMkTranslation`.`Language` (`LanguageId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_TranslationOrder_Customer`
    FOREIGN KEY (`CustomerId`)
    REFERENCES `WMkTranslation`.`Customer` (`CustomerId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_TranslationOrder_Translator`
    FOREIGN KEY (`TranslatorId`)
    REFERENCES `WMkTranslation`.`Translator` (`TranslatorId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
